- name: Cleanup
  hosts: all

  tasks:
    - name: Remove systemd unit file
      ansible.builtin.file:
        path: /etc/systemd/system/test.service
        state: absent
      become: true
      register: remove_systemd_unit_file

    - name: Reload systemd daemon
      when: remove_systemd_unit_file.changed # noqa no-handler
      ansible.builtin.systemd_service:
        daemon_reload: true
      become: true
