- name: Converge
  hosts: all

  pre_tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"
      changed_when: false

  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: trallnag.systemd_unit
      vars:
        systemd_unit_name: "test.service"
        systemd_unit_activate: true
        systemd_unit_restart: false
        systemd_unit_running_check: true
        systemd_unit_running_check_delay: "1"
        systemd_unit_content: |
          [Unit]
          Description=Test

          [Service]
          Type=simple
          ExecStart=/bin/sleep infinity

          [Install]
          WantedBy=multi-user.target
