- name: Converge
  hosts: all

  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: trallnag.systemd_unit
      vars:
        systemd_unit__name: test.service
        systemd_unit__activate: true
        systemd_unit__restart: false
        systemd_unit__running_check: true
        systemd_unit__running_check_delay: "1"
        systemd_unit__content: |
          [Unit]
          Description=Test

          [Service]
          Type=simple
          ExecStart=/bin/sleep infinity

          [Install]
          WantedBy=multi-user.target
