- name: Verify
  hosts: all

  tasks:
    - name: Check systemd unit activity
      ansible.builtin.command:
        cmd: systemctl is-active --quiet test.service # noqa command-instead-of-module
      changed_when: false
      become: true
